### PR TITLE
Replace Jaeger by Community Jaeger Operator

### PR DESCRIPTION
**Pull request by lionelmace**
I could not find **Red Hat OpenShift Jaeger**

### CODE REVIEW

**Comment by l2fprod** [comment]
@lionelmace which version of ROKS are you using?

**Comment by lionelmace** [comment]
Latest 4.8

**Comment by l2fprod** [comment]
@lionelmace 

It is there but it seems it got renamed recently

image

**Comment by l2fprod** [comment]
fixed the name

**Pull request closed without merging**
